#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


#exit 1;

cd ../../

php artisan env:check ||  exit 1;

# If there are whitespace errors, print the offending file names and fail.
#exec git diff-index --check --cached $against --
